name: Build and Release Windows App Image ZIP

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission to gradlew
        run: git update-index --chmod=+x gradlew

      - name: Build app image
        run: ./gradlew jpackage

      - name: Zip the app image
        run: |
          mkdir release
          cp -r build/jpackage/* release/
          powershell Compress-Archive -Path release\* -DestinationPath windows_app_image.zip

      - name: Upload Release ZIP
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: "Latest App Image"
          files: windows_app_image.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
